### PR TITLE
allow options and fn to be swapped

### PR DESCRIPTION
**Pull request by chadxz**
This PR replaces #1 and simply makes the (options, fn) signature an option without changing the default function signature.

### CODE REVIEW

**Comment by chadxz** [comment]
thanks @satazor ! Can you release to npm?

**Comment by satazor** [comment]
Yea give me a sec

**Comment by satazor** [comment]
Done, released a patch (0.2.9) since there was no real "new" functionality and the api is still compatible.

**Comment by chadxz** [comment]
perfect, thanks :)

**Pull request merged**
